### ISSUE TITLE
A new OWL class for Taxonomic Unit matches

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#9] opened 2018-06-05 17:47 UTC
Proposed term: `TUMatch` (class)
Superclass: [testable hypothesis](http://purl.obolibrary.org/obo/OBI_0001908)?
Definition: An assertion that two taxonomic units overlap to some extent, which can be used to store information on the match.
See also: [scratch ontology](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/ontologies/phyloref_testcase.owl#L309)

Competency questions:
* What evidence do we have that several taxonomic units overlap with or "match" each other?

**Comment by gaurav** [comment] 2019-02-07 21:35
In Model 2.0, taxonomic units are directly included in Phyloref logical expressions. For example:

    :phyloref1 owl:equivalentClass ( phyloref:excludes_TU some (
      (TaxonConcept:hasName some (TaxonName:nomenclaturalCode value ICZN)
      and (dwc:scientificName value "Tomistoma schlegii")) and ... )

They are also directly noted on a phylogeny node:

    :node1 rdf:type ( obo:CDAO_0000187 [= cdao:represents_TU] some (
       TaxonConcept:hasName some (
        obo:NOMEN_0000107 [= nomen:ICZN] and (dwc:scientificName value "Tomistoma schlegii"))))

The `CDAO_0000187` annotation (`represents_TU`) could furthermore have annotations indicating who made this assertion and on what evidence, and can be used multiple times if a single node represents multiple taxonomic units in a phylogeny -- for example, a node labeled "Homo sapiens" in a particular phylogeny might represent the species *Homo sapiens*, the genus *Homo* and the family Hominidae in a particular phylogeny if no other hominids are included elsewhere in that phylogeny. We can also assert relationships between names if we need to record a synonymy, and then annotate that assertion with the evidence used to make that assertion.

Since we no longer need taxonomic unit matches, I propose that we close this issue as resolved.

**Comment by hlapp** [comment] 2019-02-07 21:45
I anticipate that we will use GCIs to represent TU matches, not using a TUmatch class. So in principle I'm in agreement, but would like to keep this as an open issue until have an example with a corresponding reference model documented, and convinced ourselves that the logic works as intended.

**Comment by hlapp** [comment] 2021-03-24 18:40
As of today we decided to close this issue due to lack of a supporting use-case. Once a use-case does surface, we'll reopen it.

**Closed as completed by hlapp** 2021-03-24 18:40 UTC
Labels: new term, pending resolution
